name: Auto

on:
  schedule:
    - cron: "30 22 * * *" # 北京时间上午06:30
  workflow_dispatch:

env:
  COOKIE: __tea_cookie_tokens_2608=%257B%2522web_id%2522%253A%25227205452318379361847%2522%252C%2522user_unique_id%2522%253A%25227205452318379361847%2522%252C%2522timestamp%2522%253A1677650111573%257D; sid_guard=c09db832a6fa45dde5c4b3adbab7489e%7C1677813330%7C31536000%7CSat%2C+02-Mar-2024+03%3A15%3A30+GMT; uid_tt=b6d404e9308c27a5f8fd894e5cb6397f; uid_tt_ss=b6d404e9308c27a5f8fd894e5cb6397f; sid_tt=c09db832a6fa45dde5c4b3adbab7489e; sessionid=c09db832a6fa45dde5c4b3adbab7489e; sessionid_ss=c09db832a6fa45dde5c4b3adbab7489e; sid_ucp_v1=1.0.0-KGY2YzJkZDliNzcyNzQ4MmVjNWE3MzcwNmZmZTIxZjk5N2ZiODU3YjIKFwjO64C__fXtBBDSzIWgBhiwFDgCQPEHGgJsZiIgYzA5ZGI4MzJhNmZhNDVkZGU1YzRiM2FkYmFiNzQ4OWU; ssid_ucp_v1=1.0.0-KGY2YzJkZDliNzcyNzQ4MmVjNWE3MzcwNmZmZTIxZjk5N2ZiODU3YjIKFwjO64C__fXtBBDSzIWgBhiwFDgCQPEHGgJsZiIgYzA5ZGI4MzJhNmZhNDVkZGU1YzRiM2FkYmFiNzQ4OWU; store-region=cn-gd; store-region-src=uid; _tea_utm_cache_2608={%22utm_source%22:%22gold_browser_extension%22}; _tea_utm_cache_2018={%22utm_source%22:%22gold_browser_extension%22}; csrf_session_id=90f474faedb5c267f3545be98ee28508; msToken=k3M1E0BN7_VcwxNiElIgVQTLSUMcH8k--mafbSTfvxY_y7IyWGw1t-A7T1jYGYHi9DiOnJ1wMLXq7jzW9C7lNXmJMH-55VRiEhlmPh6bS2R5yheMpzDlzN85E5Xl_Ks=
  COOKIE_2: ${{ secrets.COOKIE_2 }}
  COOKIE_3: ${{ secrets.COOKIE_3 }}
  COOKIE_4: ${{ secrets.COOKIE_4 }}
  COOKIE_5: ${{ secrets.COOKIE_5 }}
  EMAIL_USER: ${{ secrets.EMAIL_USER }}
  EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
  EMAIL_TO: ${{ secrets.EMAIL_TO }}
  DINGDING_WEBHOOK: ${{ secrets.DINGDING_WEBHOOK }}
  PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
  WEIXIN_WEBHOOK: ${{ secrets.WEIXIN_WEBHOOK }}
  SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}

jobs:
  CheckIn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run Project
        run: |
          cd workflows
          yarn
          yarn checkin
#  SeaGold:
#    needs: CheckIn
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#      - name: Run Project
#        run: |
#          cd workflows
#          yarn
#          yarn seagold
